server {
    listen 80;
    server_name localhost;

    location / {
        root /run/html/seen-font-end/package/dist/;
        try_files $uri $uri/ /index.html;
    }
    location /seen-page/ {
        alias  /run/html/seen-font-end/package/dist/;
        try_files $uri $uri/ /index.html;
    }

     # 转发 seen 服务
    location /seen/ {
        proxy_pass http://seen-gateway:8080;
    }
}