serverAddr = "47.102.222.192"
serverPort = 7000

# 认证（根据服务端配置填写）
#auth.token = "e66562644a945e264a945e264a945e26"

# Web 管理面板（可选）
webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "{{ .Envs.FRPC_WEB_SERVER_PASSWORD }}"

[[proxies]]
name = "frp"
type = "tcp"
localIP = "frpc"
localPort = 7400
remotePort = 7400

[[proxies]]
name = "remote-desktop"
type = "tcp"
localIP = "192.168.0.112"
localPort = 3389
remotePort = 3389

[[proxies]]
name = "openlist"
type = "tcp"
localIP = "openlist"
localPort = 5244
remotePort = 5244

[[proxies]]
name = "tplink"
type = "tcp"
localIP = "192.168.0.1"
localPort = 80
remotePort = 6080

[[proxies]]
name = "invest-page"
type = "tcp"
localIP = "chixuehuidocker-invest-nginx"
localPort = 80
remotePort = 7080

[[proxies]]
name = "phpldapadmin-page"
type = "tcp"
localIP = "phpldapadmin"
localPort = 80
remotePort = 8280

[[proxies]]
name = "seen-page"
type = "tcp"
localIP = "chixuehuidocker-seen-nginx"
localPort = 80
remotePort = 9080