# docker-compose.yml
services:
  chixuehuidocker-invest-nginx:
    image: 'm.daocloud.io/docker.io/nginx:1.30'
    volumes:
      - '~/run:/run/html:ro'
      - '~\IdeaProjects\ricewines\home-deploy\chixuehuidocker\invest-page\nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '7080:80'
    networks:
      - shared
    restart: unless-stopped
  invest-accounting:
    command: 'java -jar app.jar --spring.profiles.active=chixuehuidocker'
    env_file:
      - 'D:\Users\CXH\data\secret\.env.secret.txt'
    image: 'm.daocloud.io/docker.io/bellsoft/liberica-runtime-container:jre-25-slim-musl'
    networks:
      - shared
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - '~/run/invest/invest-accounting/target/invest-accounting-${INVEST_VERSION}.jar:/app.jar'
      - '~/IdeaProjects/ricewines/home-deploy/chixuehuidocker/invest-page:/config'
      - 'D:\Users\CXH\data\database:/database'
    working_dir: /
  invest-macro:
    command: 'java -jar app.jar --spring.profiles.active=chixuehuidocker'
    env_file:
      - 'D:\Users\CXH\data\secret\.env.secret.txt'
    image: 'm.daocloud.io/docker.io/bellsoft/liberica-runtime-container:jre-25-slim-musl'
    networks:
      - shared
    ports:
      - "8082:8080"
    restart: unless-stopped
    volumes:
      - '~/run/invest/invest-macro/target/invest-macro-${INVEST_VERSION}.jar:/app.jar'
      - '~/IdeaProjects/ricewines/home-deploy/chixuehuidocker/invest-page:/config'
    working_dir: /
networks:
  shared:
    external: true