server {
    listen 80;
    server_name localhost;

    location / {
        rewrite ^/$ /accounting-page/ last;
    }
    location /accounting-page/ {
        alias  /run/html/accounting-page/package/dist/;
        try_files $uri $uri/ /accounting-page/index.html;
    }

    location /invest-admin-page/ {
        alias  /run/html/invest-admin-page/package/dist/;
        try_files $uri $uri/ /invest-admin-page/index.html;
    }

     # 转发 accounting 服务
    location /invest/accounting/api/ {
        proxy_pass http://accounting:8080;
    }

    # 转发 macro 服务
    location /invest/macro/api/ {
        proxy_pass http://macro:8080;
    }
}